module.exports = {
    COOKIE_KEYS: ["ADD cookies keys here"], 
    GOOGLE_APP_ID :'GET IT FROM GOOGLE',
    GOOGLE_APP_SECRET : 'GET IT FROM GOOGLE',
    FACEBOOK_APP_ID : 'GET IT FROM FB',
    FACEBOOK_APP_SECRET : 'GET IT FROM FB',
    PARTNER_1_KEY:'INTEGRATION KEY'
}